foreground #f4ceaa
background #1a272a
selection_foreground #d0baaa
selection_background #33515d
url_color #58606b

scrollback_lines 0



cursor #f4ceaa
cursor_text_color #1a272a

#black
color0 #1a272a
color8 #1a272a

#red
color1 #841a20
color9 #841a20

#teal
color2 #2b7b82
color10 #345c64

#yellow
color3 #345c64
color11 #345c64

#blue
color4 #86a2ae
color12 #86a2ae

#salmon
color5 #ffb0ab
color13 #ffb0ab

#brown
color6 #8e432c
color14 #8e432c

#white
color7 #d0baaa
color15 #f4ceaa
